## 문제

1. 다음과 같은 모양을 가지는 array를 만들어 보세요.
```
[12 13 14 15 16 17 18 19 20]
```

2. (1)에서 만든 array와 `enumerate`를 사용하여, array 각 원소에 index를 추가한 `list`를 만들어 보세요.
```
[(0, 12), (1, 13), (2, 14), (3, 15), (4, 16), (5, 17), (6, 18), (7, 19), (8, 20)]
```

3. 다음과 같은 모양을 가지는 array를 만들어 보세요.
```
[10  9  8  7  6  5  4  3  2  1]
```

4. (3)에서 만든 array와 `map`을 사용하여, array 각 원소를 제곱한 `list`를 만들어 보세요. (힌트. `lambda` 함수 사용)
```
[100, 81, 64, 49, 36, 25, 16, 9, 4, 1]
```

5. 다음과 같은 모양을 가지는 array를 만들고, 그 아래 array 같이 바꿔보세요.
```
[ 1  2  3  4  5  6  7  8  9 10]
```
```
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
```

6. 다음과 같이 2차원 array를 만들고, array의 열에 대한 평균값을 구한 뒤, 그 평균값을 소수점 넷째 자리까지 순서대로 출력하는 함수 `mean_axis_1`을 만드세요.
```python
  def mean_axis_1(arr):
    ...

  rg = np.random.default_rng(1)
  sample = rg.random((3, 4))
  """
  sample 은 [[0.51182162 0.9504637  0.14415961 0.94864945]
              [0.31183145 0.42332645 0.82770259 0.40919914]
              [0.54959369 0.02755911 0.75351311 0.53814331]]
  """
  mean_axis_1(sample)
```
```
  0.4577
  0.4671
  0.5751
  0.6320
```

7. `0` 부터 `2` 까지 총 10개의 원소 간격으로 나눠진 array를 구해보세요.
```
[0.         0.22222222 0.44444444 0.66666667 0.88888889 1.11111111
 1.33333333 1.55555556 1.77777778 2.        ]
```



In [ ]:
import numpy as np

In [ ]:
# 첫번째 문제
arr = np.arange(12, 21)
print(arr)

[12 13 14 15 16 17 18 19 20]


In [ ]:
# 두번째 문제
print(list(enumerate(arr)))

[(0, 12), (1, 13), (2, 14), (3, 15), (4, 16), (5, 17), (6, 18), (7, 19), (8, 20)]


In [ ]:
# 세번째 문제
arr2 = np.arange(1, 11)
print(arr2)
reversed_arr2 = arr2[::-1]
print(reversed_arr2)

[ 1  2  3  4  5  6  7  8  9 10]
[10  9  8  7  6  5  4  3  2  1]


In [ ]:
# np.arange(10, 0, -1)
print(np.array(sorted(arr2, reverse=True)))

[10  9  8  7  6  5  4  3  2  1]


In [ ]:
# 네번째 문제
print(list(map(lambda x: x ** 2, reversed_arr2)))

[100, 81, 64, 49, 36, 25, 16, 9, 4, 1]


In [ ]:
# 다섯번째 문제
arr3 = np.arange(1, 11)
print(arr3)
reshaped_arr = arr3.reshape(2, 5)
print(reshaped_arr)

arr3.resize((2, 5))
print(arr3)

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
# 여섯번째 문제
def mean_axis_1(arr):
  result = np.mean(arr, axis=0)
  for x in result:
    print('{:.4f}'.format(x))

rg = np.random.default_rng(1)
sample = rg.random((3, 4))
"""
sample 은 
[[0.51182162 0.9504637 0.14415961 0.94864945]
[0.31183145 0.42332645 0.82770259 0.40919914]
[0.54959369 0.02755911 0.75351311 0.53814331]]

"""
# print(sample)
mean_axis_1(sample)

0.4577
0.4671
0.5751
0.6320


In [ ]:
# 일곱번째 문제
np.linspace(0, 2, 10)

array([0.        , 0.22222222, 0.44444444, 0.66666667, 0.88888889,
       1.11111111, 1.33333333, 1.55555556, 1.77777778, 2.        ])

## Advanced indexing and index tricks
### Indexing with Arrays of Indices

In [ ]:
import numpy as np

In [ ]:
a = np.arange(12)**2                       # the first 12 square numbers
print(a)

[  0   1   4   9  16  25  36  49  64  81 100 121]


In [ ]:
i = np.array([1, 1, 3, 8, 5])              # indices 배열, 
print(a[i])                                # i 번째에 위치한 a의 원소, [a[1], a[1], a[3], a[8], a[5]]

[ 1  1  9 64 25]


In [ ]:
j = np.array([[3, 4], [9, 7]])            # bi(2)dimensional array 형태의 indices 배열
print(a[j])                             # [[a[3], a[4]],[a[9], a[7]]]

[[ 9 16]
 [81 49]]


In [ ]:
palette = np.array([[0, 0, 0],         # black 
                    [255, 0, 0],       # red
                    [0, 255, 0],       # green
                    [0, 0, 255],       # blue
                    [255, 255, 255]])  # white
print(palette.shape)

image = np.array([[0, 1, 2, 0],        # each value corresponds to a color in the palette
                   [0, 3, 4, 0]])   # palette[0]
print(image.shape)

(5, 3)
(2, 4)


In [ ]:
palette[0]
palette[1]

array([255,   0,   0])

In [ ]:
print(palette[image])
print(palette[image].shape)

[[[  0   0   0]
  [255   0   0]
  [  0 255   0]
  [  0   0   0]]

 [[  0   0   0]
  [  0   0 255]
  [255 255 255]
  [  0   0   0]]]
(2, 4, 3)


###  다수의 다차원 index 

In [ ]:
a = np.arange(12).reshape(3,4)
print(a)

i = np.array([[0, 1],                     # a의 첫번째 차원에 대한 indices  
              [1, 2]])
j = np.array([[2, 1],                     # a의 두번째 차원에 대한 indices  
              [3, 3]])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
print(a[i, j])

[[ 2  5]
 [ 7 11]]


In [ ]:
print(a[i, 2])

[[ 2  6]
 [ 6 10]]


In [ ]:
I = (i, j)  # tuple로 묶으면 하나로 사용 가능 (list 는 deprecated)
print(a[I])

[[ 2  5]
 [ 7 11]]


## `argmax`, `argmin`, `all`, `any`


`argmax`와 `argmin`: 최대값 그리고 최소값의 인덱스

In [ ]:
arg_sample = np.random.randint(50, size=10,)
print(arg_sample)

[14 48  6 15  0 45  0 31  7  1]


In [ ]:
max_idx = np.argmax(arg_sample)
print(max_idx, arg_sample[max_idx])

min_idx = np.argmin(arg_sample)
print(min_idx, arg_sample[min_idx])

1 48
4 0


`all`: 배열 전체 또는 특정 축(axis)에 대한 원소들이 모두 True 면 True 반환

`any`: 열 전체 또는 특정 축(axis)에 대한 원소들이 하나라도 True 면 True 반환

In [ ]:
arr_sample_2 = (10 + 5 * np.random.randn(12)).reshape(4, 3)  # randn range check
print(arr_sample_2)

[[ 7.25241006  9.07140032 17.28039003]
 [13.89491    11.25405588  3.51071663]
 [11.94737509 10.0727679   6.41245128]
 [ 4.67462314 11.97059431  7.43321773]]


In [ ]:
over_ten = arr_sample_2 >= 10
print(over_ten)

[[False False  True]
 [ True  True False]
 [ True  True False]
 [False  True False]]


In [ ]:
np.all(over_ten, axis=0)

array([False, False, False])

In [ ]:
np.any(over_ten, axis=0)

array([ True,  True,  True])

#### 다차원 array에 대한 `argmax`

In [ ]:
data = np.sin(np.arange(20)).reshape(5,4) 
print(data)
print(data.shape)

[[ 0.          0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155   0.6569866 ]
 [ 0.98935825  0.41211849 -0.54402111 -0.99999021]
 [-0.53657292  0.42016704  0.99060736  0.65028784]
 [-0.28790332 -0.96139749 -0.75098725  0.14987721]]
(5, 4)


In [ ]:
index = np.argmax(data, axis=0)
print(index)

[2 0 3 1]


In [ ]:
np_argmax_data = data[index, range(data.shape[1])] # => data[index[0],0], data[index[1],1]...
print(np_argmax_data)

[0.98935825 0.84147098 0.99060736 0.6569866 ]


In [ ]:
np_max_data = np.max(data, axis=0)
print(np_max_data)
print(np.all(np_argmax_data == np_max_data))
print(np_argmax_data == np_max_data)

[0.98935825 0.84147098 0.99060736 0.6569866 ]
True
[ True  True  True  True]
