In [ ]:
import numpy as np

## array 값 변경하기


In [ ]:
a = np.arange(5)
print(a)
ls = [1,3,4]
a[ls] = 0
print(a)

[0 1 2 3 4]
[0 0 2 0 0]


동일한 Index 가 여러번 사용되면, 가장 나중의 값만 적용 

In [ ]:
a = np.arange(5)
a[[0,0,2]]=[1,2,3]
print(a)

[2 1 3 3 4]


In [ ]:
a = np.arange(5)
a[[0,0,2]] += 1   # a[0] = a[0] + 1 를 동시에 수행 
print(a)

[1 1 3 3 4]


## 논리형 array를 이용한 indexing

In [ ]:
# Example 1
a = np.arange(12).reshape(3,4)
print('a : \n',a)
b = a > 4                 # b 는 a와 동일한 shape
print('\n a > 4 :\n', b) 

a : 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 a > 4 :
 [[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]


In [ ]:
print(a[b])  # a[a > 4]

[ 5  6  7  8  9 10 11]


In [ ]:
a[b] = 0

print(a)

[[0 1 2 3]
 [4 0 0 0]
 [0 0 0 0]]


In [ ]:
# 12월 6일 일요일 아침 실습 문제
none_with_np = np.array([[2, None, 6, None], [None, 3, 9, 1], [None, 3, None, None]])
print(none_with_np)

[[2 None 6 None]
 [None 3 9 1]
 [None 3 None None]]


In [ ]:
none_with_np[none_with_np == None] = 0
print(none_with_np)

[[2 0 6 0]
 [0 3 9 1]
 [0 3 0 0]]


In [ ]:
# Example 2
a = np.arange(12).reshape(3, 4)
print(a)
b1 = np.array([False, True, True])            # 첫번째 차원 선택
b2 = np.array([True, False, True, False])     # 두번째 차원 선택

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
print(a[b1, :])                               # selecting rows

[[ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
print(a[:, b2])                               # selecting columns          

[[ 0  2]
 [ 4  6]
 [ 8 10]]


In [ ]:
# Example 3 (각 학생의 (국어, 영어, 수학, 과학) 성적)
class_arr = np.array(["1학년", "2학년", "3학년", "1학년", "3학년", "2학년"])
score = np.array([[10, 20, 30, 40],
                  [8, 15, 24, 31],
                  [5, 11, 20, 25],
                  [6, 9, 1, 17],
                  [10, 17, 21, 27],
                  [9, 13, 27, 31]])

print(class_arr)
print(score)

['1학년' '2학년' '3학년' '1학년' '3학년' '2학년']
[[10 20 30 40]
 [ 8 15 24 31]
 [ 5 11 20 25]
 [ 6  9  1 17]
 [10 17 21 27]
 [ 9 13 27 31]]


In [ ]:
print(score >= 30)

score[score >= 30] = 100

[[False False  True  True]
 [False False False  True]
 [False False False False]
 [False False False False]
 [False False False False]
 [False False False  True]]


In [ ]:
print(score)

[[ 10  20 100 100]
 [  8  15  24 100]
 [  5  11  20  25]
 [  6   9   1  17]
 [ 10  17  21  27]
 [  9  13  27 100]]


In [ ]:
print((class_arr == "1학년"))

[ True False False  True False False]


In [ ]:
print((class_arr == "2학년"))

[False  True False False False  True]


![image](https://i.stack.imgur.com/nl0W8.jpg)

In [ ]:
# | -> OR 라는 뜻
print( (class_arr == "1학년") | (class_arr == "2학년") )  
# safe rule by operate order

[ True  True False  True False  True]


In [ ]:
# 1학년 또는 2학년을 찾는 indexing
print(score[(class_arr == "1학년") | (class_arr == "2학년")])

[[ 10  20 100 100]
 [  8  15  24 100]
 [  6   9   1  17]
 [  9  13  27 100]]


## `np.where`

`where(condition, [x, y])`
조건 `condition` 이 옳으면, `x` 선택, 그렇지 않으면 `y`를 선택한다.

In [ ]:
xarr = np.array([1,2,3,4,5])
yarr = np.array([6,7,8,9,10])
zarr = np.array(["서울", "경기", "서울", "인천", "경기"])
result = [ x if z == "서울" else y for x, y, z in zip(xarr, yarr, zarr) ]
print(result)

[1, 7, 3, 9, 10]


In [ ]:
where_result = np.where(zarr=="서울", xarr, yarr)
print(where_result)

[ 1  7  3  9 10]


In [ ]:
rg = np.random.default_rng(1)

arr1 = np.floor((70 + 20 * rg.random(12))).reshape(4, 3)
arr2 = np.floor((10 + 20 * rg.random(12))).reshape(4, 3)
print('arr1 \n', arr1)
print('\n arr2 \n', arr2)

arr1 
 [[80. 89. 72.]
 [88. 76. 78.]
 [86. 78. 80.]
 [70. 85. 80.]]

 arr2 
 [[16. 25. 16.]
 [19. 12. 18.]
 [14. 15. 25.]
 [15. 19. 29.]]


In [ ]:
result = np.where(arr1 >= 80, arr2, 0) 
print(result)

[[16. 25.  0.]
 [19.  0.  0.]
 [14.  0. 25.]
 [ 0. 19. 29.]]


## numpy fancy indexing
정수 배열을 indexer로 사용해서 다차원 배열로 부터 Indexing하는 방법

In [ ]:
rg = np.random.default_rng(1)
arr1 = np.floor((20 * rg.random(24))).reshape(6, 4)
print(arr1)

[[10. 19.  2. 18.]
 [ 6.  8. 16.  8.]
 [10.  0. 15. 10.]
 [ 6. 15.  6.  9.]
 [ 2.  8.  4.  5.]
 [15.  5.  9. 19.]]


In [ ]:
print(arr1[[2, 3, 5]])          # 3행, 4행, 6행 순서로 선택

[[10.  0. 15. 10.]
 [ 6. 15.  6.  9.]
 [15.  5.  9. 19.]]


In [ ]:
print(arr1[[-1, -4, -2]])        # 음(negative)의 index는 뒤에서 부터 선택

[[15.  5.  9. 19.]
 [10.  0. 15. 10.]
 [ 2.  8.  4.  5.]]


In [ ]:
print(arr1[[2, 3, 5], [1, 0, 2]])   # (2,1), (3,0), (5,2)의 원소 선택

[0. 6. 9.]


### np.ix_
N 개의 1차원 array에 대한 cross product를 index할 때 사용

In [ ]:
arr1[np.ix_([2, 3, 5], [1, 0, 2])]

array([[ 0., 10., 15.],
       [15.,  6.,  6.],
       [ 5., 15.,  9.]])

In [ ]:
first_ix, second_ix = np.ix_([2, 3, 5], [1, 0, 2])
print(first_ix, first_ix.shape)
print(second_ix, second_ix.shape)

[[2]
 [3]
 [5]] (3, 1)
[[1 0 2]] (1, 3)


### 1번 문제
다음과 같은 2차원 array `arr`가 있습니다.

  ```python
    arr = np.arange(1, 51).reshape(5, 10)
    """
    [[ 1  2  3  4  5  6  7  8  9 10]
      [11 12 13 14 15 16 17 18 19 20]
      [21 22 23 24 25 26 27 28 29 30]
      [31 32 33 34 35 36 37 38 39 40]
      [41 42 43 44 45 46 47 48 49 50]]
    """
  ```


  * 아래와 같은 결과가 나오도록 array를 **slicing** 해보세요.
  1. 
  ```
[[21 22 23 24 25 26 27 28 29 30]
[31 32 33 34 35 36 37 38 39 40]]
  ```
  2.
  ```
[[ 5  6]
[15 16]
[25 26]
[35 36]
[45 46]]
  ```
  3.
  ```
[[13 14 15 16 17]
[23 24 25 26 27]]
  ```


  * 아래와 같은 결과가 나오도록 array를 **indexing** 해보세요.  
  1.  `25`보다 큰 값 (힌트. 논리형 index 활용)
  ```
  [26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]
  ```
  2. fancy indexing 활용
  ```
  [ 1, 12, 23, 34, 45]
  ```
  3. `ix_` 활용 (또는 slicing 활용해도 풀 수 있음)
  ```
  [[41 42 43 44 45]
    [31 32 33 34 35]
    [21 22 23 24 25]
    [11 12 13 14 15]
    [ 1  2  3  4  5]]
  ```



### 2번 문제

다음과 같은 3차원 array `arr`가 있습니다.

```python
arr = np.arange(1, 41).reshape(2, 4, 5)
"""
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]
  [31 32 33 34 35]
  [36 37 38 39 40]]]
"""
```


   * 아래와 같은 결과가 나오도록 array를 **slicing** 해보세요.  
  
  1.    

  ```
    [[[16 17 18 19 20]]
    
    [[36 37 38 39 40]]]
  ```
  2.
  ```
    [[[ 5]
      [10]
      [15]
      [20]]
        
    [[25]
     [30]
     [35]
     [40]]]
    ```
  3.

    ```
    [[[13 14]
      [18 19]]]
    ```



 * 아래와 같은 결과가 나오도록 array의 값을 바꿔보세요.  
  1.  20 보다 작은 값을 100으로 수정
  ```
    [[[100 100 100 100 100]
      [100 100 100 100 100]
      [100 100 100 100 100]
      [100 100 100 100  20]]
    
    [[ 21  22  23  24  25]
      [ 26  27  28  29  30]
      [ 31  32  33  34  35]
      [ 36  37  38  39  40]]]
  ```

### 3번 문제

다음과 같은 두 개의 1차원 array `arr1`, `arr2`가 있습니다.

```python
arr1 = np.arange(1, 11)
#  [ 1  2  3  4  5  6  7  8  9 10]
arr2 = np.arange(11, 21)
#  [11 12 13 14 15 16 17 18 19 20]
```

  * 아래와 같은 결과가 나오도록 두 array의 shape를 바꾸어 합쳐보세요. (`vstack` 또는 `hstack` 활용)
  1. 
  ```
    [[ 1  2  3  4  5]
    [ 6  7  8  9 10]
    [11 12 13 14 15]
    [16 17 18 19 20]]
  ```
  2.

  ```
  [[ 1  2 11 12]
  [ 3  4 13 14]
  [ 5  6 15 16]
  [ 7  8 17 18]
  [ 9 10 19 20]]
  ```



### 4번 문제

임의의 2차원 array `arr`에 대해, 첫번째 axis 에 대한 `numpy.argmin`를 수행하고, 수행된 결과를 이용하여 찾은 최소값과 `numpy.min` 값이 동일함을 `numpy.all`을 통하여 보이세요.

  ```python
rg = np.random.default_rng(1)
arr = 10*rg.random((3,4))
print('주어진 arr는 \n', arr)
...
print('첫번째 axis에 대한 argmin은 \n', idx)
...
print('argmin 결과를 통해 찾은 최소값은 \n', min_val)
...
print('numpy.min 과 동일한지 np.all을 통해서 확인 \n', result)
  ```
  ```
주어진 arr는 
[[5.11821625 9.50463696 1.44159613 9.48649447]
[3.11831452 4.23326449 8.27702594 4.09199136]
[5.49593688 0.27559113 7.53513109 5.38143313]]

첫번째 axis에 대한 argmin은
[1 2 0 1]

argmin 결과를 통해 찾은 최소값은
[3.11831452 0.27559113 1.44159613 4.09199136]

numpy.min 과 동일한지 np.all을 통해서 확인
True
  ```


In [ ]:
# 1번 문제 정답

arr = np.arange(1, 51).reshape(5, 10)

print(arr)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]]


In [ ]:
print(arr[2:4, :])

[[21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]]


In [ ]:
print(arr[:, 4:6])

[[ 5  6]
 [15 16]
 [25 26]
 [35 36]
 [45 46]]


In [ ]:
print(arr[1:3, 2:7])

[[13 14 15 16 17]
 [23 24 25 26 27]]


In [ ]:
b = arr > 25

print(arr[b])

[26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49
 50]


In [ ]:
i = [0,1,2,3,4]
print(i)
i = list(range(5))
print(i)
j = i

print(arr[(i, j)])

[0, 1, 2, 3, 4]
[0, 1, 2, 3, 4]
[ 1 12 23 34 45]


In [ ]:
idx = np.ix_(i[::-1], i)
print(arr[idx])

[[41 42 43 44 45]
 [31 32 33 34 35]
 [21 22 23 24 25]
 [11 12 13 14 15]
 [ 1  2  3  4  5]]


In [ ]:
print(arr[-1:-6:-1, 0:5])

[[41 42 43 44 45]
 [31 32 33 34 35]
 [21 22 23 24 25]
 [11 12 13 14 15]
 [ 1  2  3  4  5]]


In [ ]:
# 2번 문제 정답
arr = np.arange(1, 41).reshape(2, 4, 5)

print(arr)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]
  [31 32 33 34 35]
  [36 37 38 39 40]]]


In [ ]:
print(arr[0:2, 3:, :])

[[[16 17 18 19 20]]

 [[36 37 38 39 40]]]


In [ ]:
print(arr[0:2, :, 4:])

[[[ 5]
  [10]
  [15]
  [20]]

 [[25]
  [30]
  [35]
  [40]]]


In [ ]:
print(arr[0:1, 2:4, 2:4])

[[[13 14]
  [18 19]]]


In [ ]:
it = arr < 20

arr[it] = 100

print(arr)

[[[100 100 100 100 100]
  [100 100 100 100 100]
  [100 100 100 100 100]
  [100 100 100 100  20]]

 [[ 21  22  23  24  25]
  [ 26  27  28  29  30]
  [ 31  32  33  34  35]
  [ 36  37  38  39  40]]]


In [ ]:
# 3번 문제 정답
arr1 = np.arange(1, 11)
# [ 1 2 3 4 5 6 7 8 9 10]

arr2 = np.arange(11, 21)
# [11 12 13 14 15 16 17 18 19 20]

In [ ]:
print(np.vstack( (arr1.reshape(2, 5), arr2.reshape(2, 5)) ))


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [ ]:
print(np.hstack( (arr1.reshape(5, 2), arr2.reshape(5, 2))))


[[ 1  2 11 12]
 [ 3  4 13 14]
 [ 5  6 15 16]
 [ 7  8 17 18]
 [ 9 10 19 20]]


In [ ]:
# 4번 문제 정답
rg = np.random.default_rng(1)
arr = 10*rg.random((3,4))
print('주어진 arr는 \n', arr)


주어진 arr는 
 [[5.11821625 9.50463696 1.44159613 9.48649447]
 [3.11831452 4.23326449 8.27702594 4.09199136]
 [5.49593688 0.27559113 7.53513109 5.38143313]]


In [ ]:
idx = np.argmin(arr, axis=0)

print('첫번째 axis에 대한 argmin은 \n', idx)

첫번째 axis에 대한 argmin은 
 [1 2 0 1]


In [ ]:
min_val = arr[idx, list(range(4))]
print('argmin 결과를 통해 찾은 최소값은 \n', min_val)

argmin 결과를 통해 찾은 최소값은 
 [3.11831452 0.27559113 1.44159613 4.09199136]


In [ ]:
npmin = np.min(arr, axis=0)
result = npmin == min_val
result = np.all(result)
print('numpy.min 과 동일한지 np.all을 통해서 확인 \n', result)

numpy.min 과 동일한지 np.all을 통해서 확인 
 True
